// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNOxjclNvKdNb-XIUKwDalC8q0ZDjO8NY',
    appId: '1:751857482469:web:12ca4f93867024a134720c',
    messagingSenderId: '751857482469',
    projectId: 'ai-exam-analysis',
    authDomain: 'ai-exam-analysis.firebaseapp.com',
    storageBucket: 'ai-exam-analysis.appspot.com',
    measurementId: 'G-Y1DDGPG9E4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkAOQXCXLnmgBTMtWeipJqljYRPOKF8P4',
    appId: '1:751857482469:android:8ccfae69422b0c8b34720c',
    messagingSenderId: '751857482469',
    projectId: 'ai-exam-analysis',
    storageBucket: 'ai-exam-analysis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6hniuIwDAmAXe7fytVk3UBCzjHaLcwuE',
    appId: '1:751857482469:ios:c892fa9cc336576434720c',
    messagingSenderId: '751857482469',
    projectId: 'ai-exam-analysis',
    storageBucket: 'ai-exam-analysis.appspot.com',
    iosClientId: '751857482469-h6m6s9sr1e7sqcohe6b0qf43irkq3pag.apps.googleusercontent.com',
    iosBundleId: 'education.advantageous.aiExamAnalysis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6hniuIwDAmAXe7fytVk3UBCzjHaLcwuE',
    appId: '1:751857482469:ios:9797e18ac9d7336634720c',
    messagingSenderId: '751857482469',
    projectId: 'ai-exam-analysis',
    storageBucket: 'ai-exam-analysis.appspot.com',
    iosClientId: '751857482469-bfg71j5f676sclvraie3gkkh16n6goqu.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiExamAnalysis',
  );
}
